# Question

Will the code work? Why or why not?

```js
const getUsers = async () => {
  const url = 'https://jsonplaceholder.typicode.com/users';
  const users = await fetch(url).then(r => r.json()).catch((err) => []);
  console.log(users)
  return users;
}
getUsers()
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer
I initially thought that this script will work, because inside of the users await, you have the fetch, the conversion, and the catch being run in one line. console.log(users) must await the data returned from that promise before running it, instead of depending on a .then() to deliver this data afterwards.

I was right!

# Teacher Feedback