# Question

Is this function safe? Why or why not?

```js
const getUser = async (userId) => {
  const url = `https://jsonplaceholder.typicode.com/users/${userId}`;
  const response = await fetch(url);
  const users = await response.json();
  console.log(users)
  return users;
}
getUser(-1)
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer
I initially concluded that this function isn't safe, because while it uses await to wait for the data to be fetched and translated into JS, and then returns the product, there's no catch to save the function from any errors and to save the whole program from stopping completely. I was correct, because running the code returned nothing (since a user id shouldn't be able to be negative). Had there been some conditions checking the value and a catch to handle errors, this would've ran a bit smoother. 

I was right!

# Teacher Feedback
Score: 3/3
Great!